name: CivPvP
authors: [TeaJizzle, Maxopoly]
version: 1.0
main: com.gimmicknetwork.civpvpinventory.CivpvpInventory

depend: [NameLayer]

commands:
  inv:
    description: "Save/load inventories."
    usage: "Usage: /inv save/load <inventory> or /inv clear."
    permission: civpvpinventory.use
  duel:
    description: Requests to duel someone
    usage: /duel <playername>
    permission: civpvpinventory.use
  accept:
    description: Accept the last duel request
    usage: /accept
    permission: civpvpinventory.use

permissions:
  civpvpinventory.use:
    description: "use inventory saving/loading."
    default: true
  civpvp.badmin:
    description: "Admin crimes inc"
    default: op